### ISSUE TITLE
Can't compile Scramble

### ISSUE THREAD

**Issue by Mirrorman95** [supremetakoyaki/Scramble#1]
There's no solution file here. I don't know how to compile this without an .sln file. I wouldn't bother trying to compile it myself, except the source codes of ntwewy-db.dll and Scramble were both updated two hours ago, but while a new dll release was uploaded to its repository with it two hours ago, by contrast the Scramble releases were last updated two days ago. Also, the dll's source code has a .sln file in its repository, making it even more odd Scramble's does not. I really like this program, and maybe there's just some way to compile it without an sln file that I'm just not seeing, so if there is I'm really sorry for that. But if not, this repository may need to be updated accordingly.

**Comment by supremetakoyaki** [comment]
Oops, I'm sorry about that. For some reason the .sln and .csproj files were ignored. Please check the newest commit. Let me know if you have any issues.

**Comment by Mirrorman95** [comment]
Thanks, but now it won't let me compile because it can't find twewy-db. I've made many attempts to tell it where my local copy of the dll is, but it refuses to use it. I've tried everything I can think of, but still no luck. Is it possible you could put a tutorial in the readme explaining which folder to put the twewy-db.dll in or how to point the project to it so it will compile?

Microsoft Visual Studio Community 2019 Preview Version 16.11.0 Preview 3.0 also gives me this error when I try to add the dll:
Invalid command line switch for "csc.exe". System.ArgumentException: MSB3053: The assembly alias "[MY FOLDER]\Scramble.0.6\ntwewy-db.dll" on reference "[MY FOLDER]\ntwewy-db\ntwewy-db\bin\Debug\net5.0\ntwewy-db.dll" contains illegal characters.

Even after I compiled the dll myself and used that version instead, it still gave that error.

**Comment by supremetakoyaki** [comment]
Hi. Sorry for the delay.

Try removing the reference to ntwewy-db in the project dependencies -> assemblies (this is in the solution explorer), and then re-add it. 

I will try to replicate this later and let you know if I find something. Seems to be a Visual Studio bug.

**Comment by Mirrorman95** [comment]
That did it! I can compile it now. Thanks!
