### ISSUE TITLE
Sortting Fuction

### ISSUE THREAD

**Issue by ChucklesTheJester** [supremetakoyaki/Scramble#3]
hello, is there any possible way to have it so that things can be sorted to make searching easier?

**Comment by supremetakoyaki** [comment]
I will add it 👍

**Comment by ChucklesTheJester** [comment]
oh, one more thing, in the collection editor, the only choices for everything is obtained and seen, but can it be possible to add a mastered choice for the pins? as that seems to be what the grafitis for mastering pins relies on

**Comment by supremetakoyaki** [comment]
Yes, I am aware that it's something that's missing. I will work on it :)
I'll close this issue after dropping the next release.

**Comment by supremetakoyaki** [comment]
New version released! I close this issue.
