### ISSUE TITLE
 .NET 5.0 Runtime not seen

### ISSUE THREAD

**Issue by ferrika** [supremetakoyaki/Scramble#4]
Sorry to bother you, but every time I try to use the save editor after double clicking on the .exe file it asks me to install  .NET 5.0 Runtime even though I have installed it and tried reinstalling it 5 times already .

![image](https://user-images.githubusercontent.com/89782149/131334865-ee937234-8dfa-42ac-b17a-bf0f55370b37.png)

Am I missing something?

I have tried on a friends pc too, installed .NET 5.0.9 and it gave me the same popup

**Comment by supremetakoyaki** [comment]
Hi there!
You probably are installing the wrong runtime (do not confuse ASP.NET Runtime and Desktop Runtime)

I assume you are using Windows 10 (64 bits).
Try installing this one: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.9-windows-x64-installer
Let me know if this is the case.

nevertheless, I'm thinking of targetting .NET 4.8 instead; that way the program could work on Linux too.

**Comment by ferrika** [comment]
Thank you so much! 
I feel so stupid right now, I was installing the one on the left because i though it was the only windows option while middle was linux. 
My bad.
![image](https://user-images.githubusercontent.com/89782149/131641814-1b54bc08-c0db-428e-8131-f14656512dc7.png)

Again thank you so much! It is working perfectly now
