### ISSUE TITLE
Neo: legendary headphones clothing disappears from inventory

### ISSUE THREAD

**Issue by eternalshades** [supremetakoyaki/Scramble#6]
Modifying PC save for "Neo: The World Ends With You".

After making some changes, reloaded the save file and noticed the Legendary Headphones disappeared from my inventory in game.

When I try to add them back in the Clothing Editor, it appears to get re-added, but simply exiting the Clothing Editor menu and re-entering the Clothing Editor and the item is gone from my inventory again.

Legendary Headphone ID is `0`
EMPTY_CLOTHING_ID is also `0` here: https://github.com/supremetakoyaki/Scramble/blob/main/Forms/ClothingInventoryEditor.cs#L19
Seems likely there is a check somewhere in the editor that is validating that the item ID is valid, and it doesn't take accept `0` as a valid ID.

**Comment by supremetakoyaki** [comment]
Addressed in the newest release. Thank you
